version: '3'

services:
    rundeck:
        build:
            context: ./
            args:
                RUNDECK_IMAGE: ${RUNDECK_IMAGE:-jordan/rundeck:3.0.23}
        environment:
            RUNDECK_GRAILS_URL: http://127.0.0.1:4440
            EXTERNAL_SERVER_URL: http://127.0.0.1:4440
            RUNDECK_ADMIN_PASSWORD: 23df87sdfjhb23

        ports:
          - 4440:4440
        volumes:
          - ./data/var/lib/mysql:/var/lib/mysql
          - ./data/etc/rundeck:/etc/rundeck
          - ./data/var/rundeck:/var/rundeck
          - ./data/var/lib/rundeck/.ssh:/var/lib/rundeck/.ssh
          - ./data/var/log/rundeck:/var/log/rundeck
          - ./data/opt/rundeck-plugins:/opt/rundeck-plugins
          - ./data/var/lib/rundeck/logs:/var/lib/rundeck/logs
          - ./data/var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage
          - /var/run/docker.sock:/var/run/docker.sock:ro
